/*
 * Copyright (c) 2012, The President and Fellows of Harvard College.
 * All Rights Reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *  1. Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *
 *  2. Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *
 *  3. Neither the name of the University nor the names of its contributors
 *     may be used to endorse or promote products derived from this software
 *     without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE UNIVERSITY AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE UNIVERSITY OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: State.proto

package filterd.protocol;

public final class KinematicState {
  private KinematicState() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class State extends
      com.google.protobuf.GeneratedMessage {
    // Use State.newBuilder() to construct.
    private State() {
      initFields();
    }
    private State(boolean noInit) {}
    
    private static final State defaultInstance;
    public static State getDefaultInstance() {
      return defaultInstance;
    }
    
    public State getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return filterd.protocol.KinematicState.internal_static_filterd_protocol_State_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return filterd.protocol.KinematicState.internal_static_filterd_protocol_State_fieldAccessorTable;
    }
    
    // required uint32 frameNum = 1;
    public static final int FRAMENUM_FIELD_NUMBER = 1;
    private boolean hasFrameNum;
    private int frameNum_ = 0;
    public boolean hasFrameNum() { return hasFrameNum; }
    public int getFrameNum() { return frameNum_; }
    
    // required bool occluded = 2;
    public static final int OCCLUDED_FIELD_NUMBER = 2;
    private boolean hasOccluded;
    private boolean occluded_ = false;
    public boolean hasOccluded() { return hasOccluded; }
    public boolean getOccluded() { return occluded_; }
    
    // required double locX = 3;
    public static final int LOCX_FIELD_NUMBER = 3;
    private boolean hasLocX;
    private double locX_ = 0D;
    public boolean hasLocX() { return hasLocX; }
    public double getLocX() { return locX_; }
    
    // required double locY = 4;
    public static final int LOCY_FIELD_NUMBER = 4;
    private boolean hasLocY;
    private double locY_ = 0D;
    public boolean hasLocY() { return hasLocY; }
    public double getLocY() { return locY_; }
    
    // required double locZ = 5;
    public static final int LOCZ_FIELD_NUMBER = 5;
    private boolean hasLocZ;
    private double locZ_ = 0D;
    public boolean hasLocZ() { return hasLocZ; }
    public double getLocZ() { return locZ_; }
    
    // required double orientQuatX = 6;
    public static final int ORIENTQUATX_FIELD_NUMBER = 6;
    private boolean hasOrientQuatX;
    private double orientQuatX_ = 0D;
    public boolean hasOrientQuatX() { return hasOrientQuatX; }
    public double getOrientQuatX() { return orientQuatX_; }
    
    // required double orientQuatY = 7;
    public static final int ORIENTQUATY_FIELD_NUMBER = 7;
    private boolean hasOrientQuatY;
    private double orientQuatY_ = 0D;
    public boolean hasOrientQuatY() { return hasOrientQuatY; }
    public double getOrientQuatY() { return orientQuatY_; }
    
    // required double orientQuatZ = 8;
    public static final int ORIENTQUATZ_FIELD_NUMBER = 8;
    private boolean hasOrientQuatZ;
    private double orientQuatZ_ = 0D;
    public boolean hasOrientQuatZ() { return hasOrientQuatZ; }
    public double getOrientQuatZ() { return orientQuatZ_; }
    
    // required double orientQuatW = 9;
    public static final int ORIENTQUATW_FIELD_NUMBER = 9;
    private boolean hasOrientQuatW;
    private double orientQuatW_ = 0D;
    public boolean hasOrientQuatW() { return hasOrientQuatW; }
    public double getOrientQuatW() { return orientQuatW_; }
    
    // required double orientEulerX = 10;
    public static final int ORIENTEULERX_FIELD_NUMBER = 10;
    private boolean hasOrientEulerX;
    private double orientEulerX_ = 0D;
    public boolean hasOrientEulerX() { return hasOrientEulerX; }
    public double getOrientEulerX() { return orientEulerX_; }
    
    // required double orientEulerY = 11;
    public static final int ORIENTEULERY_FIELD_NUMBER = 11;
    private boolean hasOrientEulerY;
    private double orientEulerY_ = 0D;
    public boolean hasOrientEulerY() { return hasOrientEulerY; }
    public double getOrientEulerY() { return orientEulerY_; }
    
    // required double orientEulerZ = 112;
    public static final int ORIENTEULERZ_FIELD_NUMBER = 112;
    private boolean hasOrientEulerZ;
    private double orientEulerZ_ = 0D;
    public boolean hasOrientEulerZ() { return hasOrientEulerZ; }
    public double getOrientEulerZ() { return orientEulerZ_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasFrameNum) return false;
      if (!hasOccluded) return false;
      if (!hasLocX) return false;
      if (!hasLocY) return false;
      if (!hasLocZ) return false;
      if (!hasOrientQuatX) return false;
      if (!hasOrientQuatY) return false;
      if (!hasOrientQuatZ) return false;
      if (!hasOrientQuatW) return false;
      if (!hasOrientEulerX) return false;
      if (!hasOrientEulerY) return false;
      if (!hasOrientEulerZ) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasFrameNum()) {
        output.writeUInt32(1, getFrameNum());
      }
      if (hasOccluded()) {
        output.writeBool(2, getOccluded());
      }
      if (hasLocX()) {
        output.writeDouble(3, getLocX());
      }
      if (hasLocY()) {
        output.writeDouble(4, getLocY());
      }
      if (hasLocZ()) {
        output.writeDouble(5, getLocZ());
      }
      if (hasOrientQuatX()) {
        output.writeDouble(6, getOrientQuatX());
      }
      if (hasOrientQuatY()) {
        output.writeDouble(7, getOrientQuatY());
      }
      if (hasOrientQuatZ()) {
        output.writeDouble(8, getOrientQuatZ());
      }
      if (hasOrientQuatW()) {
        output.writeDouble(9, getOrientQuatW());
      }
      if (hasOrientEulerX()) {
        output.writeDouble(10, getOrientEulerX());
      }
      if (hasOrientEulerY()) {
        output.writeDouble(11, getOrientEulerY());
      }
      if (hasOrientEulerZ()) {
        output.writeDouble(112, getOrientEulerZ());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasFrameNum()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getFrameNum());
      }
      if (hasOccluded()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getOccluded());
      }
      if (hasLocX()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, getLocX());
      }
      if (hasLocY()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, getLocY());
      }
      if (hasLocZ()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, getLocZ());
      }
      if (hasOrientQuatX()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, getOrientQuatX());
      }
      if (hasOrientQuatY()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, getOrientQuatY());
      }
      if (hasOrientQuatZ()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, getOrientQuatZ());
      }
      if (hasOrientQuatW()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, getOrientQuatW());
      }
      if (hasOrientEulerX()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, getOrientEulerX());
      }
      if (hasOrientEulerY()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(11, getOrientEulerY());
      }
      if (hasOrientEulerZ()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(112, getOrientEulerZ());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static filterd.protocol.KinematicState.State parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static filterd.protocol.KinematicState.State parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static filterd.protocol.KinematicState.State parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static filterd.protocol.KinematicState.State parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static filterd.protocol.KinematicState.State parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static filterd.protocol.KinematicState.State parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static filterd.protocol.KinematicState.State parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static filterd.protocol.KinematicState.State parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static filterd.protocol.KinematicState.State parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static filterd.protocol.KinematicState.State parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(filterd.protocol.KinematicState.State prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private filterd.protocol.KinematicState.State result;
      
      // Construct using filterd.protocol.KinematicState.State.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new filterd.protocol.KinematicState.State();
        return builder;
      }
      
      protected filterd.protocol.KinematicState.State internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new filterd.protocol.KinematicState.State();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return filterd.protocol.KinematicState.State.getDescriptor();
      }
      
      public filterd.protocol.KinematicState.State getDefaultInstanceForType() {
        return filterd.protocol.KinematicState.State.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public filterd.protocol.KinematicState.State build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private filterd.protocol.KinematicState.State buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public filterd.protocol.KinematicState.State buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        filterd.protocol.KinematicState.State returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof filterd.protocol.KinematicState.State) {
          return mergeFrom((filterd.protocol.KinematicState.State)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(filterd.protocol.KinematicState.State other) {
        if (other == filterd.protocol.KinematicState.State.getDefaultInstance()) return this;
        if (other.hasFrameNum()) {
          setFrameNum(other.getFrameNum());
        }
        if (other.hasOccluded()) {
          setOccluded(other.getOccluded());
        }
        if (other.hasLocX()) {
          setLocX(other.getLocX());
        }
        if (other.hasLocY()) {
          setLocY(other.getLocY());
        }
        if (other.hasLocZ()) {
          setLocZ(other.getLocZ());
        }
        if (other.hasOrientQuatX()) {
          setOrientQuatX(other.getOrientQuatX());
        }
        if (other.hasOrientQuatY()) {
          setOrientQuatY(other.getOrientQuatY());
        }
        if (other.hasOrientQuatZ()) {
          setOrientQuatZ(other.getOrientQuatZ());
        }
        if (other.hasOrientQuatW()) {
          setOrientQuatW(other.getOrientQuatW());
        }
        if (other.hasOrientEulerX()) {
          setOrientEulerX(other.getOrientEulerX());
        }
        if (other.hasOrientEulerY()) {
          setOrientEulerY(other.getOrientEulerY());
        }
        if (other.hasOrientEulerZ()) {
          setOrientEulerZ(other.getOrientEulerZ());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setFrameNum(input.readUInt32());
              break;
            }
            case 16: {
              setOccluded(input.readBool());
              break;
            }
            case 25: {
              setLocX(input.readDouble());
              break;
            }
            case 33: {
              setLocY(input.readDouble());
              break;
            }
            case 41: {
              setLocZ(input.readDouble());
              break;
            }
            case 49: {
              setOrientQuatX(input.readDouble());
              break;
            }
            case 57: {
              setOrientQuatY(input.readDouble());
              break;
            }
            case 65: {
              setOrientQuatZ(input.readDouble());
              break;
            }
            case 73: {
              setOrientQuatW(input.readDouble());
              break;
            }
            case 81: {
              setOrientEulerX(input.readDouble());
              break;
            }
            case 89: {
              setOrientEulerY(input.readDouble());
              break;
            }
            case 897: {
              setOrientEulerZ(input.readDouble());
              break;
            }
          }
        }
      }
      
      
      // required uint32 frameNum = 1;
      public boolean hasFrameNum() {
        return result.hasFrameNum();
      }
      public int getFrameNum() {
        return result.getFrameNum();
      }
      public Builder setFrameNum(int value) {
        result.hasFrameNum = true;
        result.frameNum_ = value;
        return this;
      }
      public Builder clearFrameNum() {
        result.hasFrameNum = false;
        result.frameNum_ = 0;
        return this;
      }
      
      // required bool occluded = 2;
      public boolean hasOccluded() {
        return result.hasOccluded();
      }
      public boolean getOccluded() {
        return result.getOccluded();
      }
      public Builder setOccluded(boolean value) {
        result.hasOccluded = true;
        result.occluded_ = value;
        return this;
      }
      public Builder clearOccluded() {
        result.hasOccluded = false;
        result.occluded_ = false;
        return this;
      }
      
      // required double locX = 3;
      public boolean hasLocX() {
        return result.hasLocX();
      }
      public double getLocX() {
        return result.getLocX();
      }
      public Builder setLocX(double value) {
        result.hasLocX = true;
        result.locX_ = value;
        return this;
      }
      public Builder clearLocX() {
        result.hasLocX = false;
        result.locX_ = 0D;
        return this;
      }
      
      // required double locY = 4;
      public boolean hasLocY() {
        return result.hasLocY();
      }
      public double getLocY() {
        return result.getLocY();
      }
      public Builder setLocY(double value) {
        result.hasLocY = true;
        result.locY_ = value;
        return this;
      }
      public Builder clearLocY() {
        result.hasLocY = false;
        result.locY_ = 0D;
        return this;
      }
      
      // required double locZ = 5;
      public boolean hasLocZ() {
        return result.hasLocZ();
      }
      public double getLocZ() {
        return result.getLocZ();
      }
      public Builder setLocZ(double value) {
        result.hasLocZ = true;
        result.locZ_ = value;
        return this;
      }
      public Builder clearLocZ() {
        result.hasLocZ = false;
        result.locZ_ = 0D;
        return this;
      }
      
      // required double orientQuatX = 6;
      public boolean hasOrientQuatX() {
        return result.hasOrientQuatX();
      }
      public double getOrientQuatX() {
        return result.getOrientQuatX();
      }
      public Builder setOrientQuatX(double value) {
        result.hasOrientQuatX = true;
        result.orientQuatX_ = value;
        return this;
      }
      public Builder clearOrientQuatX() {
        result.hasOrientQuatX = false;
        result.orientQuatX_ = 0D;
        return this;
      }
      
      // required double orientQuatY = 7;
      public boolean hasOrientQuatY() {
        return result.hasOrientQuatY();
      }
      public double getOrientQuatY() {
        return result.getOrientQuatY();
      }
      public Builder setOrientQuatY(double value) {
        result.hasOrientQuatY = true;
        result.orientQuatY_ = value;
        return this;
      }
      public Builder clearOrientQuatY() {
        result.hasOrientQuatY = false;
        result.orientQuatY_ = 0D;
        return this;
      }
      
      // required double orientQuatZ = 8;
      public boolean hasOrientQuatZ() {
        return result.hasOrientQuatZ();
      }
      public double getOrientQuatZ() {
        return result.getOrientQuatZ();
      }
      public Builder setOrientQuatZ(double value) {
        result.hasOrientQuatZ = true;
        result.orientQuatZ_ = value;
        return this;
      }
      public Builder clearOrientQuatZ() {
        result.hasOrientQuatZ = false;
        result.orientQuatZ_ = 0D;
        return this;
      }
      
      // required double orientQuatW = 9;
      public boolean hasOrientQuatW() {
        return result.hasOrientQuatW();
      }
      public double getOrientQuatW() {
        return result.getOrientQuatW();
      }
      public Builder setOrientQuatW(double value) {
        result.hasOrientQuatW = true;
        result.orientQuatW_ = value;
        return this;
      }
      public Builder clearOrientQuatW() {
        result.hasOrientQuatW = false;
        result.orientQuatW_ = 0D;
        return this;
      }
      
      // required double orientEulerX = 10;
      public boolean hasOrientEulerX() {
        return result.hasOrientEulerX();
      }
      public double getOrientEulerX() {
        return result.getOrientEulerX();
      }
      public Builder setOrientEulerX(double value) {
        result.hasOrientEulerX = true;
        result.orientEulerX_ = value;
        return this;
      }
      public Builder clearOrientEulerX() {
        result.hasOrientEulerX = false;
        result.orientEulerX_ = 0D;
        return this;
      }
      
      // required double orientEulerY = 11;
      public boolean hasOrientEulerY() {
        return result.hasOrientEulerY();
      }
      public double getOrientEulerY() {
        return result.getOrientEulerY();
      }
      public Builder setOrientEulerY(double value) {
        result.hasOrientEulerY = true;
        result.orientEulerY_ = value;
        return this;
      }
      public Builder clearOrientEulerY() {
        result.hasOrientEulerY = false;
        result.orientEulerY_ = 0D;
        return this;
      }
      
      // required double orientEulerZ = 112;
      public boolean hasOrientEulerZ() {
        return result.hasOrientEulerZ();
      }
      public double getOrientEulerZ() {
        return result.getOrientEulerZ();
      }
      public Builder setOrientEulerZ(double value) {
        result.hasOrientEulerZ = true;
        result.orientEulerZ_ = value;
        return this;
      }
      public Builder clearOrientEulerZ() {
        result.hasOrientEulerZ = false;
        result.orientEulerZ_ = 0D;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:filterd.protocol.State)
    }
    
    static {
      defaultInstance = new State(true);
      filterd.protocol.KinematicState.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:filterd.protocol.State)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_filterd_protocol_State_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_filterd_protocol_State_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013State.proto\022\020filterd.protocol\"\353\001\n\005Stat" +
      "e\022\020\n\010frameNum\030\001 \002(\r\022\020\n\010occluded\030\002 \002(\010\022\014\n" +
      "\004locX\030\003 \002(\001\022\014\n\004locY\030\004 \002(\001\022\014\n\004locZ\030\005 \002(\001\022" +
      "\023\n\013orientQuatX\030\006 \002(\001\022\023\n\013orientQuatY\030\007 \002(" +
      "\001\022\023\n\013orientQuatZ\030\010 \002(\001\022\023\n\013orientQuatW\030\t " +
      "\002(\001\022\024\n\014orientEulerX\030\n \002(\001\022\024\n\014orientEuler" +
      "Y\030\013 \002(\001\022\024\n\014orientEulerZ\030p \002(\001B\020B\016Kinemat" +
      "icState"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_filterd_protocol_State_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_filterd_protocol_State_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_filterd_protocol_State_descriptor,
              new java.lang.String[] { "FrameNum", "Occluded", "LocX", "LocY", "LocZ", "OrientQuatX", "OrientQuatY", "OrientQuatZ", "OrientQuatW", "OrientEulerX", "OrientEulerY", "OrientEulerZ", },
              filterd.protocol.KinematicState.State.class,
              filterd.protocol.KinematicState.State.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
